---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt: 
      name: apache2
      state: absent

  - name: Add php support for apache
    apt:
      name: libapache2-mod-php
      state: absent

